import os
import sys
import importlib.util
import inspect
import pandas as pd
from typing import Any, Callable, Dict, List, Tuple, Optional

# Base directory for strategies
STRATEGY_DIR = os.path.dirname(os.path.abspath(__file__))

class StrategyRegistry:
    """
    Central registry for all strategies.
    Dynamically loads strategies from:
    1. strategies/xscript/price_volume/*.py
    2. strategies/xscript/pattern/*.py
    3. strategies/auto_generated/strat_06_籌碼選股.py (Class methods)
    """
    _strategies: Dict[str, Dict[str, Callable]] = {}
    _initialized = False

    @classmethod
    def initialize(cls):
        """Load all strategies if not already loaded"""
        if cls._initialized:
            return
            
        print("[StrategyRegistry] Initializing strategies...")
        cls._strategies = {
            "04_Price_Volume": {},
            "05_Pattern": {},
            "06_Chip": {},
            "00_Legacy": {},
            "00_XScript_Common": {},
            "XQ_Composable_Technical": {},
            "XQ_Composable_Chip": {}
        }
        
        # 1. Load File-based Strategies (Category 04 & 05)
        cls._load_file_strategies("xscript/price_volume", "04_Price_Volume")
        cls._load_file_strategies("xscript/pattern", "05_Pattern")
        
        # 2. Load Class-based Strategies (Category 06)
        cls._load_class_strategies()
        
        # 3. Load Common XScript Strategies (Technical Indicators)
        cls._load_xscript_common_strategies()

        # 4. Load composable indicator modules used by the XQ-style scanner.
        cls._load_composable_indicator_strategies()

        # 5. Load Auto-Generated XScript Strategies (Recursive)
        cls._load_recursive_strategies("auto_generated", "AutoGenerated")
        
        cls._initialized = True
        print(f"[StrategyRegistry] Loaded {sum(len(v) for v in cls._strategies.values())} strategies.")

    @classmethod
    def _load_recursive_strategies(cls, relative_path: str, base_category: str):
        """Recursively load strategies from a directory structure"""
        root_path = os.path.join(STRATEGY_DIR, relative_path)
        if not os.path.exists(root_path):
            print(f"[StrategyRegistry] Directory not found: {root_path}")
            return
            
        for root, dirs, files in os.walk(root_path):
            for fname in files:
                if fname.endswith('strategies.py'):
                    # Calculate category from path relative to STRATEGY_DIR
                    # e.g. strategies/auto_generated/選股/p_11_選股機器人/strategies.py
                    # category -> "選股/11.選股機器人" (derived from dir structure)
                    
                    full_path = os.path.join(root, fname)
                    rel_to_root = os.path.relpath(root, root_path)
                    
                    if rel_to_root == '.':
                        category = base_category
                    else:
                        # Normalize path separators and cleanup
                        category = rel_to_root.replace(os.sep, '/')
                    
                    # Store in _strategies under this category
                    # We might need to ensure the dictionary exists
                    if category not in cls._strategies:
                        cls._strategies[category] = {}
                        
                    cls._load_module_strategies(full_path, category)

    @classmethod
    def _load_module_strategies(cls, file_path: str, category: str):
        """Load strategies from a specific file into a category"""
        try:
            # Generate unique module name based on path
            rel_path = os.path.relpath(file_path, STRATEGY_DIR)
            module_name = "strat_" + rel_path.replace(os.sep, "_").replace(".py", "")
            
            spec = importlib.util.spec_from_file_location(module_name, file_path)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                
                # Inspect for Strategy Classes (auto-generated ones)
                for name, obj in inspect.getmembers(module, inspect.isclass):
                    # Class name usually ends with 'Strategies'
                    if name.endswith('Strategies'):
                        for method_name, method in inspect.getmembers(obj):
                            # Methods that obey the strategy signature
                            if not method_name.startswith('_') and callable(method):
                                # Check signature roughly
                                if hasattr(method, '__code__') and method.__code__.co_argcount >= 1:
                                    cls._strategies[category][method_name] = method
                                    
        except Exception as e:
            print(f"[StrategyRegistry] Error loading {file_path}: {e}")

    @classmethod
    def get_strategy_tree(cls) -> Dict:
        """
        Return a nested dictionary representing the implementation structure.
        Format: { 'Category': { 'SubCategory': { ... 'StrategyName': 'FUNCTION_NAME' ... } } }
        """
        if not cls._initialized:
            cls.initialize()
            
        tree = {}
        for category, strats in cls._strategies.items():
            # Parse category path "選股/p_11_選股機器人"
            parts = category.split('/')
            
            current_node = tree
            for part in parts:
                if part not in current_node:
                    current_node[part] = {}
                current_node = current_node[part]
            
            # Add strategies as a special key or just mix them in?
            # Let's use a special key `__strategies__` to distinguish from subdirs
            current_node['__strategies__'] = sorted(list(strats.keys()))
            
        return tree

    @classmethod
    def _load_file_strategies(cls, relative_path: str, category: str):
        """Load strategies from .py files in a directory"""
        target_dir = os.path.join(STRATEGY_DIR, relative_path)
        if not os.path.exists(target_dir):
            print(f"[StrategyRegistry] Directory not found: {target_dir}")
            return

        for fname in os.listdir(target_dir):
            if not fname.endswith('.py') or fname.startswith('__'):
                continue
                
            file_path = os.path.join(target_dir, fname)
            module_name = os.path.splitext(fname)[0]
            
            try:
                # Dynamic Import
                spec = importlib.util.spec_from_file_location(module_name, file_path)
                if spec and spec.loader:
                    module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(module)
                    
                    # Find strategy function
                    # Heuristic: Function name matches filename (simplified) 
                    # OR find the main public function that takes 'df'
                    func = cls._find_strategy_func(module, module_name)
                    
                    if func:
                        # Use filename or function name as display name
                        display_name = module_name.replace("_", " ") # e.g. "投信_大買" -> "投信 大買"
                        cls._strategies[category][display_name] = func
                        
            except Exception as e:
                print(f"[StrategyRegistry] Error loading {fname}: {e}")

    @classmethod
    def _find_strategy_func(cls, module, module_name):
        """Find the strategy function in a module"""
        # 1. Try exact match
        if hasattr(module, module_name):
            return getattr(module, module_name)
            
        # 2. Search for valid function
        for name, obj in inspect.getmembers(module, inspect.isfunction):
            if name.startswith('_'): continue
            if obj.__module__ != module.__name__: continue
            
            # Simple check: arg name or type hint
            sig = inspect.signature(obj)
            params = list(sig.parameters.values())
            if len(params) > 0 and ('df' in params[0].name or 'DataFrame' in str(params[0].annotation)):
                return obj
        return None

    @classmethod
    def _load_class_strategies(cls):
        """Load strategies from known classes (e.g. Category 06)"""
        try:
            # Import strictly inside method to avoid circular imports if any
            # Adjust path if needed. 
            root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            if root_dir not in sys.path:
                sys.path.append(root_dir)
                
            from strategies.auto_generated.strat_06_籌碼選股 import Cat06籌碼選股Strategies
            
            for name in dir(Cat06籌碼選股Strategies):
                if name.startswith('_'): continue
                attr = getattr(Cat06籌碼選股Strategies, name)
                
                if callable(attr):
                    # Check if it looks like a strategy (takes df, returns tuple)
                    # For now just trust the class structure
                    cls._strategies["06_Chip"][name] = attr
                    
        except ImportError as e:
            print(f"[StrategyRegistry] Could not load Category 06: {e}")
        except Exception as e:
            print(f"[StrategyRegistry] Error loading class strategies: {e}")

    @classmethod
    def _load_xscript_common_strategies(cls):
        """Load common XScript strategies (Technical Indicators)"""
        try:
             # Add project root to path if needed (though already handled in engine usually)
            root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            if root_dir not in sys.path:
                sys.path.append(root_dir)
                
            from strategies.xscript_strategies import XScriptStrategies
            
            # Map method names to display names if needed, or use docstrings/names
            # Original ScannerEngine mapping:
            # 'XScript - Price/Vol High': XScriptStrategies.price_volume_high
            # 'XScript - Momentum Breakout': XScriptStrategies.momentum_breakout
            # 'XScript - 3 Red Soldiers': XScriptStrategies.red_soldiers
            # 'XScript - 價量齊揚': XScriptStrategies.price_volume_surge
            # 'XScript - MA黃金交叉': XScriptStrategies.ma_golden_cross
            # etc.
            
            # We can expose all static methods
            for name in dir(XScriptStrategies):
                if name.startswith('_'): continue
                attr = getattr(XScriptStrategies, name)
                
                if callable(attr):
                    # Use function name or a mapped display name?
                    # Let's use a simple mapping or just the name for now.
                    # Ideally we want "XScript - Momentum Breakout" etc.
                    # But for dynamic loading, maybe we just use the function name formatted nicely?
                    # Let's map known ones to preserve UI consistency
                    
                    display_name = f"XScript - {name.replace('_', ' ').title()}"
                    
                    # Specific overrides for consistency with legacy UI
                    overrides = {
                        'price_volume_high': 'XScript - Price/Vol High',
                        'momentum_breakout': 'XScript - Momentum Breakout',
                        'red_soldiers': 'XScript - 3 Red Soldiers',
                        'price_volume_surge': 'XScript - 價量齊揚',
                        'ma_golden_cross': 'XScript - MA黃金交叉',
                        'macd_golden_cross': 'XScript - MACD黃金交叉',
                        'kd_golden_cross': 'XScript - KD黃金交叉',
                        'w_bottom': 'XScript - W底型態',
                        'head_and_shoulders_bottom': 'XScript - 頭肩底',
                        'volume_breakout': 'XScript - 無量變有量',
                        'ma_breakout_with_volume': 'XScript - 帶量突破均線'
                    }
                    
                    final_name = overrides.get(name, display_name)
                    
                    # Some of these belong to different categories in the UI
                    # Price/Vol, Technical, Pattern
                    # We can put them all in "00_XScript_Common" or split them?
                    # The UI mapping logic in strategy_page.py puts "00_XScript_Common" into "XScript - 技術指標"
                    # But "W底型態" is pattern.
                    # "價量齊揚" is Price/Vol.
                    
                    # Problem: The UI expects specific categories.
                    # If we dump everything into 00_XScript_Common, they all go to "Technical".
                    # We should probably split them here or update the UI mapping.
                    
                    # Let's try to categorize based on known lists
                    cat = "00_XScript_Common" # Default to Technical
                    
                    if name in ['price_volume_high', 'price_volume_surge', 'volume_breakout', 'ma_breakout_with_volume']:
                        cat = "04_Price_Volume" # Add to existing Price/Vol category
                    elif name in ['w_bottom', 'head_and_shoulders_bottom']:
                        cat = "05_Pattern" # Add to Pattern
                    
                    # Update the strategy map
                    if cat not in cls._strategies: cls._strategies[cat] = {} # Should exist
                    cls._strategies[cat][final_name] = attr
                    
        except ImportError as e:
            print(f"[StrategyRegistry] Could not load XScriptStrategies: {e}")
        except Exception as e:
             print(f"[StrategyRegistry] Error loading XScriptStrategies: {e}")

    @classmethod
    def _load_composable_indicator_strategies(cls):
        """Expose indicator-library conditions as normal scanner strategies."""
        try:
            from strategies.indicator_library import INDICATORS, evaluate_indicator

            for indicator_id, (definition, _evaluator) in INDICATORS.items():
                category = (
                    "XQ_Composable_Chip"
                    if definition.category == "chip"
                    else "XQ_Composable_Technical"
                )

                def strategy_func(df, _indicator_id=indicator_id, **kwargs):
                    chip_cache = kwargs.pop("_chip_cache", {})
                    return evaluate_indicator(_indicator_id, df, kwargs, chip_cache)

                cls._strategies[category][definition.name] = strategy_func

        except Exception as e:
            print(f"[StrategyRegistry] Error loading composable indicators: {e}")

    @classmethod
    def get_all_strategies(cls) -> Dict[str, List[str]]:
        """Return dict of Category -> List of Strategy Names"""
        if not cls._initialized:
            cls.initialize()
            
        return {cat: sorted(list(strats.keys())) for cat, strats in cls._strategies.items() if strats}

    @classmethod
    def get_strategy(cls, category: str, name: str) -> Optional[Callable]:
        """Get strategy function by category and name"""
        if not cls._initialized:
            cls.initialize()
            
        return cls._strategies.get(category, {}).get(name)

    @classmethod
    def get_strategy_params(cls, name: str) -> Dict[str, Dict]:
        """
        Get parameters for a specific strategy.
        Returns a dict: { 'param_name': {'default': val, 'type': type_name} }
        """
        if not cls._initialized:
            cls.initialize()
            
        # Find the strategy function
        strategy_func = None
        for cat, strats in cls._strategies.items():
            if name in strats:
                strategy_func = strats[name]
                break
        
        if not strategy_func:
            return {}
            
        # Inspect parameters
        sig = inspect.signature(strategy_func)
        params = {}
        
        for param_name, param in sig.parameters.items():
            # Skip self, cls, df, code, date (context params)
            if param_name in ['self', 'cls', 'df', 'code', 'date', 'args', 'kwargs']:
                continue
            
            # Skip argument if it's strictly *args or **kwargs
            if param.kind == inspect.Parameter.VAR_POSITIONAL or param.kind == inspect.Parameter.VAR_KEYWORD:
                continue
                
            param_info = {}
            
            # Default value
            if param.default != inspect.Parameter.empty:
                param_info['default'] = param.default
            else:
                # If no default, we might mark it as required, or provide a sensible default?
                # For now, let's just assume 0 or empty string if we can't determine
                param_info['default'] = 0 # Placeholder generic default
                
            # Type hint
            if param.annotation != inspect.Parameter.empty:
                # Try to get simple name
                if hasattr(param.annotation, '__name__'):
                    param_info['type'] = param.annotation.__name__
                else:
                    param_info['type'] = str(param.annotation)
            else:
                # Infer type from default if possible
                if isinstance(param_info['default'], int):
                    param_info['type'] = 'int'
                elif isinstance(param_info['default'], float):
                    param_info['type'] = 'float'
                elif isinstance(param_info['default'], bool):
                    param_info['type'] = 'bool'
                else:
                    param_info['type'] = 'str'
            
            params[param_name] = param_info
            
        return params

    @classmethod
    def _cast_param(cls, value: Any, param_type: str) -> Any:
        """Cast parameter to correct type"""
        try:
            if param_type == 'int':
                return int(value)
            elif param_type == 'float':
                return float(value)
            elif param_type == 'bool':
                if isinstance(value, str):
                    return value.lower() in ('true', '1', 'yes')
                return bool(value)
            else:
                return str(value)
        except (ValueError, TypeError):
            return value
    
    @classmethod
    def run_strategy(cls, name: str, df: pd.DataFrame, **kwargs) -> Tuple[bool, str]:
        """
        Run a strategy by name with parameter validation.
        Returns (is_match, reason)
        """
        if not cls._initialized:
            cls.initialize()
        
        # Validate and cast parameters
        expected_params = cls.get_strategy_params(name)
        validated_kwargs = {}
        
        for key, value in kwargs.items():
            # Skip internal parameters (prefixed with _)
            if key.startswith('_'):
                validated_kwargs[key] = value
                continue
                
            if key in expected_params:
                param_type = expected_params[key].get('type', 'str')
                try:
                    validated_kwargs[key] = cls._cast_param(value, param_type)
                except Exception as e:
                    print(f"[Registry] Warning: Invalid param {key}={value} for {name}: {e}")
                    # Use default value if casting fails
                    validated_kwargs[key] = expected_params[key].get('default')
            else:
                # Pass through unknown params (might be needed by strategy)
                validated_kwargs[key] = value
            
        # Search in all categories
        for cat, strats in cls._strategies.items():
            if name in strats:
                try:
                    # Pass validated kwargs to the strategy function
                    return strats[name](df, **validated_kwargs)
                except TypeError as e:
                    print(f"[Registry] TypeError running {name}: {e}")
                    # Try without kwargs as fallback
                    try:
                        return strats[name](df)
                    except:
                        return False, f"Execution Error: {str(e)}"
                except Exception as e:
                    print(f"[Registry] Error running strategy {name}: {e}")
                    return False, f"Error: {str(e)}"
                    
        return False, "Strategy not found"
    
    @classmethod
    def run_strategies_batch(cls, names: List[str], df: pd.DataFrame, strategy_params: Dict[str, Dict] = None) -> Dict[str, Tuple[bool, str]]:
        """
        Run multiple strategies on the same dataframe.
        Returns dict of {strategy_name: (is_match, reason)}
        """
        if strategy_params is None:
            strategy_params = {}
        
        results = {}
        for name in names:
            params = strategy_params.get(name, {})
            results[name] = cls.run_strategy(name, df, **params)
        
        return results

if __name__ == "__main__":
    # Test
    StrategyRegistry.initialize()
    print("Available Categories:", StrategyRegistry.get_all_strategies().keys())
    
    cats = StrategyRegistry.get_all_strategies()
    for c, s in cats.items():
        print(f"\n[{c}] ({len(s)})")
        print(", ".join(s[:5]) + ("..." if len(s)>5 else ""))
